# Configuration

config:

# MD013 - line-length

  line_length:
    line_length: 120
    code_blocks: false
    tables: false
  html:
    allowed_elements:
      - div
  descriptive-link-text: false

# Globs

globs:

- "posts/**/*.qmd"
- "*.qmd"

# Ignores

ignores:

- "_site/**/*.qmd"

# Fix any fixable errors

fix: true
