# Configuration

config:

# MD013 - line-length

  line_length:
    line_length: 120
    code_blocks: false
    tables: false
  html:
    allowed_elements:
      - div

# Globs

globs:

- "posts/**/*.qmd"
- "*.qmd"

# Ignores

ignores:

- ".markdownlint-cli2.yaml"

# Fix any fixable errors

fix: true
