project:
  type: website
  resources:
    - "*.R"
    - "*.Rmd"
    - "*.py"
    - "*.qmd"
    - "*.sh"
    - "*.yaml"
website:
  title: "ns-rse"
  navbar:
    right:
      - about.qmd
      - links.qmd
      - icon: github
        href: https://github.com/ns-rse
      - icon: twitter
        href: https://twitter.com/nshephardRSE
format:
  html:
    theme: vapor
    css: styles.css
