project:
  type: website
  resources:
    - "*.R"
    - "*.Rmd"
    - "*.py"
    - "*.qmd"
    - "*.sh"
    - "*.yaml"
website:
  title: "ns-rse"
  site-url: https://ns-rse.github.io/
  description: "Software development in a Research Environment"
  navbar:
    right:
      - about.qmd
      - links.qmd
      - icon: github
        href: https://github.com/ns-rse
      - icon: twitter
        href: https://twitter.com/nshephardRSE
      - icon: rss
        href: index.xml
format:
  html:
    theme: vapor
    css: styles.css
