project:
  type: website
  resources:
    - "*.R"
    - "*.Rmd"
    - "*.py"
    - "*.qmd"
    - "*.sh"
    - "*.yaml"
website:
  title: "blog.nshephard.dev"
  site-url: https://blog.nshephard.dev/
  description: "Software development in a Research Environment"
  navbar:
    right:
      - about.qmd
      - links.qmd
      - icon: github
        href: https://github.com/ns-rse
        rel: me
      - icon: twitter
        href: https://twitter.com/nshephardRSE
      - icon: rss
        href: index.xml
        rel: me
      - icon: mastodon
        href: https://fosstodon.org/@nshephard
        rel: me
format:
  html:
    theme:
      light: pulse
      dark: solar
    css: styles.css
author:
  - name: Neil Shephard
    orcid: 0000-0001-8301-6857
listing:
  contents: posts
  sort: "date desc"
  type: default
  feed:
    categories:
      - python
      - git
      - github
      - code
  sort-ui: false
  filter-ui: false
filters:
  - openlinksinnewpage
